### ISSUE TITLE
Support Digest Authentication for proxies

### ISSUE THREAD

**Issue by abrahampm** [Debian/apt#103]
**Describe the issue**
I'm facing an issue trying to configure apt to download files from archive.ubuntu.com repository through a corporate proxy which only support Digest Authentication, not Basic Authentication available.

**System Environment**
Ubuntu 18.04 64bit.

**APT version**
apt 1.6.8 (amd64)

**Additional context**
I set the apt proxy (file /etc/apt/apt.conf) this way:
`Acquire::http::Proxy "http://user:password@proxy:port";`
`Acquire::https::Proxy "https://user:password@proxy:port";`

Then when I run sudo apt update I get this:
`Err:1 http://cu.archive.ubuntu.com/ubuntu bionic InRelease`
`  407  Proxy Authentication Required [IP: xx.xx.xx.xx xxxx]`
`Err:2 http://cu.archive.ubuntu.com/ubuntu bionic-updates InRelease`
`  407  Proxy Authentication Required [IP: xx.xx.xx.xx xxxx]`

I checked my password many times, it's correct.
I tried also replacing special characters in my passwords with percent encoded characters but didn't have luck.
I think this issue is probably related with the authentication type that the proxy uses.
In my University the only way to connect to internet is through the proxy.
Hopefully someone can help me,
Any help will be appreciated.

**Comment by julian-klode** [comment]
Adding support for digest authentication is not feasible.

**Comment by abrahampm** [comment]
So which workaround should I try?
