### ISSUE TITLE
apt-get does not bypass proxy unconditionally allthough configured to do so

### ISSUE THREAD

**Issue by Bigaunti** [Debian/apt#104]
Hope this is not a duplicate issue, did not run into such report so far.

Situation:

MyPC ------------------|
This is all local Net--|  |------- SomeProxy ---> internet
SomeNas -------------|

My Debian repository is stored on SomeNas.

On MyPC:

- Environment variables http_proxy, https_proxy, ftp_proxy are set, as well as the no_proxy variable
- Always
- Even if the proxy is not up and running
- Which happens frequently as just that frequently the internet is not needed

- Debian is configured to access My Debian repository over ftp
- so in sources.list this entry: deb ftp://SomeNas/DebianVersion stable main contrib
- In /etc/apt/apt.conf.d/20NoProxy
- there this is configured:
- Acquire::ftp::Proxy::SomeNas "DIRECT";
 - (but to me it seems that Acquire::ftp::Proxy DIRECT;  works just as well)
- (in fact my impresion is it works also without that /etc/apt/apt.conf.d/20NoProxy configuration file - but did not test this extensively)

Now apt-get 'something' works perfectly as long as the proxy is up and running.
Not if that SomeProxy is down.

I wonder if this behaviour is wanted that way.
Or is it not wrong to expect the apg-get proces to completely ignore the proxy in this setup?

Sniffing the network traffic does indeed confirm apt-get to contact the proxy each time on the proxy port.
As soon as it received an acknowledge from the proxy it proceeds to contact SomeNas directly, things work fine.

When the proxy is down, apt-get returns: connection to SomeProxy failed, and the apt-get process aborts.

Most recently noticed this in Debian 9.11.0, but also in older version backwards unto Squeeze (or was it even Lenny? - not sure now anymore).

Is this worth investigating?

Please give a hint where in the source code to find the place where this can be adjusted.

Thanks in advance for your attention and efforts.

**Comment by julian-klode** [comment]
FTP ist not supported. Especially not with a proxy, there are no ftp proxies.

**Comment by Bigaunti** [comment]
I'm sorry I expressed myself unclear apparently.

I do not ask for proxy support itself - apt has it and it works fine.
A little bit to fine in fact. 

The configuration to disable proxying the network traffic does not as I expected.

Despite setting this: Acquire::ftp::Proxy::MyNas "DIRECT";
in /etc/apt/apt.conf.d/20NoProxy
apt-get will first contact SomeProxy.
After apt-get got a reply from SomeProxy it continues to contact SomeNas and do whatever was requested to do.
If apt-get does not receive a reply from SomeProxy, it aborts the process.

As a workaround untill now, I do unset the environment variable http_proxy manually on MyPC before using apt-get (or dselect).
So apt wil not contact the SomeProxy in the first place when doing update or a package install.

Where can I find the spot in the apt code where the process 'decides' to contact the proxy,
even when this is supposed to be set off by that configuration item Acquire::ftp::Proxy::SomeNas "DIRECT";

Sorry for the misunderstanding.

Regards.

Gert
