### ISSUE TITLE
Add ability to specify arbitrary sysroot

### ISSUE THREAD

**Issue by RPGillespie6** [Debian/apt#106]
In embedded systems, it's a big pain to get packages installed on boards that do not have internet access.

Say I have something like an [EspressoBin](http://espressobin.net/) connected to my PC. The board is running custom linux, and doesn't have (easy) internet access.

Wouldn't it be nice if I could run:

```
apt install git:arm64 --sysroot ./espresso_bin_sysroot
```
Which would install arm64 version of git _and its dependencies_ to `espresso_bin_sysroot`. In other words, after the operation were complete,  `espresso_bin_sysroot` would contain all of the appropriate binaries and .so files under:
```
espresso_bin_sysroot/
    etc/
    usr/
    var/
    share/
```

I could then rsync that sysroot to my cross-compiling toolchain's sysroot and also the EspressoBin's rootfs instead of having to spend hours fiddling around with recipes in Yocto Project or Buildroot.

**Comment by julian-klode** [comment]
There a various options to configure various things, such as Dir and RootDir. Note that all essential packages must be installed in the root dir.

**Comment by RPGillespie6** [comment]
I will try tinkering around with that but I'm having a hard time finding documentation on these configuration options... could you give an example of how I might install arm64 version of git to an arbitrary directory?

**Comment by julian-klode** [comment]
You have to debootstrap a minimal Debian system into there first.

**Comment by DonKult** [comment]
What you are asking for is universal [support for DPKG_ROOT](https://wiki.debian.org/Teams/Dpkg/Spec/InstallBootstrap) as a package installation is not just unpacking a few files, but also running maintainerscripts and co. We will hopefully get there at some point, but I wouldn't exactly hold my breath for it just yet.

You don't need that for your usecase though. As Julian already said you can bootstrap a chroot, edit that to your hearts content and then move that elsewhere. Read up on "foreign" and usage of qemu to e.g. create an armhf chroot on your amd64 machine. You might want to contact one of the various support channels if you have further questions.

**Comment by RPGillespie6** [comment]
Thanks for the tips, I'll check it out. I already have a yocto-generated sysroot for arm64; my current solution for quickly installing arm64 packages to the board involves manually downloading the `.deb` files and extracting them to the rootfs which seems to work well enough. I was hoping `apt` would be able to do automatically what I am doing manually which is why I checked here first. Maybe chroot is the solution I'm looking for.
