### ISSUE TITLE
How to cross compile apt-source 

### ISSUE THREAD

**Issue by jundahzijone** [Debian/apt#11]
how to cross compile the apt-source to arm architecture

**Comment by julian-klode** [comment]
Well, you can pass --host, --target and --build to configure like with other autotools projects. Getting a configure script without running it without arguments is a bit complicated if you're not using a tarball, but this should work:

```
make configure buildlib/config.sub buildlib/config.guess
cd build
../configure --host=... --target=... --build=...
touch configure-stamp
```

Then you can run make from the top-level directory. But also see #12.

Once we have a normal build system (CMake or normal autotools), things will be normal
