### ISSUE TITLE
apt-get update error

### ISSUE THREAD

**Issue by Mingli-Yu** [Debian/apt#112]
apt 2.1.6 failed as below:
Could not create temporary file for /buildarea1/net/wr_build/root-fs-test/buildarea1/musttry-why/build/justspace/auto-system-level_package_deb_next/200611/lxbuilds/Harcuvar_platform_up/intel-x86-64-standard-glibc-std/mytest/build/tmp-glibc/work/intel_x86_64-wrs-linux/mytest-image-std/1.0-r5/apt/lists/partial/buildarea1_net_wr%5fbuild_root-fs-test_buildarea1_musttry-why_build_justspace_auto-system-level%5fpackage%5fdeb%5fnext_200611_lxbuilds_Harcuvar%5fplatform%5fup_intel-x86-64-standard-glibc-std_mytest_build_tmp-glibc_work_intel%5fx86%5f64-wrs-linux_mytest-image-std_1.0-r5_oe-rootfs-repo_all._Packages - mkstemp (36: File name too long)

**Comment by julian-klode** [comment]
Your path is too long, that's not a bug in apt.

**Comment by Mingli-Yu** [comment]
Thanks your update!
But I can use this long path with apt 1.2.31.
