### ISSUE TITLE
apt-get update problem

### ISSUE THREAD

**Issue by QairexStudio** [Debian/apt#117]
when i say that: `sudo apt-get update`
i will coming this error:
`Ignore: 1 http://ppa.launchpad.net/webupd8team/y-ppa-manager/ubuntu groovy InRelease
Error: 2 http://ppa.launchpad.net/webupd8team/y-ppa-manager/ubuntu groovy Release
  404 Not Found [IP: ]
The same: 3 http://packages.microsoft.com/repos/vscode stable InRelease
The same: 4 https://download.mono-project.com/repo/debian vs-buster InRelease
The same: 5 http://kali.download/kali kali-rolling InRelease
Reading the package lists ... Done
E: No Release file in the 'http://ppa.launchpad.net/webupd8team/y-ppa-manager/ubuntu groovy Release' repository.
N: It is not possible to update securely from such a repository, so the repository has been disabled.
N: For detailed information about storage creation and user configuration, apt-secure (8) can be found in the directory page.`

**Comment by julian-klode** [comment]
If you'd stopped to think a minute before reporting a bug, or optimally did your due diligence before upgrading, you might have realized that you're running a development release of Ubuntu and that none of these third-party repositories has built packages for it.

**Comment by QairexStudio** [comment]
Dude Sorry but i cant understand it.
