### ISSUE TITLE
IntelliJ and pycharm installation

### ISSUE THREAD

**Issue by eshwarRA** [Debian/apt#119]
I don’t know if this is the right place to leave this request but can you please make it possible for Debian users to install IntelliJ and pycharm ide using apt install

**Comment by DonKult** [comment]
It isn't the right place. You could write a RFP (request for packaging) in the Debian BTS (bug tracking system) … or, actually they exist already with relatively low activity: [RFP: idea-free -- Java IDE with intelligent code editor and various refactorings](https://bugs.debian.org/560159) and [RFP: pycharm -- IDE for python development](https://bugs.debian.org/742394).

As Debian is a docracy (= the people who do the work rule the place) requests tend to fall by the wayside if nobody takes an immediate liking but luckily the requester is usually the best candidate for taking an interest… if you want to look into packaging there is a multitude of documentation on how to get started (I would suggest not starting which such seemingly big packages, though). And as everything is better in a team, the Debian Python team was recently formed (by a merger of two related groups) so you should contact them for more help.
