### ISSUE TITLE
configure vs. config.status --recheck

### ISSUE THREAD

**Issue by KubaKaszycki** [Debian/apt#12]
I am compiling APT on Mac OS X (I am **not** stupid, it works). I have discovered one major mistake that can affect all people who pass arguments to configure.

buildlib/configure.mak: LINE 59: `(HERE="`pwd`"; cd '$(BUILDDIR)' && "$$HERE/configure")`
This will lose all arguments given to configure. Instead, I suggest:
`HERE="$(CURDIR)"; cd '$(BUILDDIR)' && if test -f "config.status"; then ./config.status --recheck && ./config.status; else "$$HERE/configure; fi`
This will do the right.

Also mind some things:
- Parentheses were not necessary. GNU make (and most other makes) group the commands line-by-line.
- `$(CURDIR)` - This exists in GNU make. If it is not GNU make, you may also use `$(shell pwd)`. Using pwd surrounded with reverse apostrophes makes it hard to debug; see make output with silent rules disabled, with/without `$(shell)`

**Comment by julian-klode** [comment]
This change has no effect. I ran

```./configure --disable-nls```

which produces:

```checking whether NLS is requested... no```

But running `config.status --recheck` does not pass `--disable-nls`, and thus produces:

```checking whether NLS is requested... yes```

**Comment by julian-klode** [comment]
@KubaKaszycki Any idea why this had no effect for me?

**Comment by KubaKaszycki** [comment]
IDK
Maybe update Gettext & Autoconf

Anyway, this situation is strange. I am using Mac OS X, which is known for causing more corner cases. I am using homebrew'ed Autotools and Gettext, and Apple/LLVM clang++.

**Comment by KubaKaszycki** [comment]
For me, it works
I gave:
`./configure CXX=clang++`
It says:
`Running CONFIG_SHELL=/bin/sh /bin/sh ./configure CXX=clang++`

**Comment by julian-klode** [comment]
I have just switched APT over to CMake, so I'm closing this bug.

**Comment by julian-klode** [comment]
@KubaKaszycki Have you tried building one of the 1.3 RCs on macOS yet? I'm worried there are some portability issues in the new CMake-based buildsystem, some fixes (making gettext and the whole documentation stuff more optional and configurable) are in 

  https://github.com/julian-klode/apt/commits/bugfix/cmake

I'd love to hear about places where things can/need to be improved.

**Comment by KubaKaszycki** [comment]
I have built a few APT versions for Mac, I have even established a [repo](http://kaszycki.net.pl/macapt/en/). The only fix I had to apply was setting `LC_TIME` to `"C"` before parsing `"Date"` field in response, and then restoring it. It seems that OS X has strange locales, especially with formatting/parsing.

Anyways, thanks for all support with this issue.

P.S. CMake builds perfectly
