### ISSUE TITLE
apt update responds with a "500 Software caused connection abort" for http

### ISSUE THREAD

**Issue by DonFlymoor** [Debian/apt#121]
When using any http mirrors, apt update responds with **"500 Software caused connection abort"**, but any https mirror works successfully.

```shell
user@user-desktop:~$ sudo apt update
[sudo] password for user: 
Err:1 http://ppa.launchpad.net/ubuntu-pi-flavour-makers/ppa/ubuntu focal InRelease
  500  Software caused connection abort [IP: 91.189.95.83 80]
Hit:2 https://mirror.kumi.systems/ubuntu-ports focal InRelease
Reading package lists... Done
Building dependency tree       
Reading state information... Done
All packages are up to date.
W: Failed to fetch http://ppa.launchpad.net/ubuntu-pi-flavour-makers/ppa/ubuntu/dists/focal/InRelease  500  Software caused connection abort [IP: 91.189.95.83 80]
W: Some index files failed to download. They have been ignored, or old ones used instead.
```
 This is likely because of Sophos XG's http Realtime scanner, which has been known to "mess up" http.
however, curl is perfectly willing to do what apt will not.

```bash
curl http://ppa.launchpad.net/ubuntu-pi-flavour-makers/ppa/ubuntu/dists/focal/InRelease
-----BEGIN PGP SIGNED MESSAGE-----
(snip)
-----END PGP SIGNATURE-----
```

Some system information:
```bash
uname -a
Linux don-desktop 5.4.0-1015-raspi #15-Ubuntu SMP Fri Jul 10 05:34:24 UTC 2020 aarch64 aarch64 aarch64 GNU/Linux
```

**Comment by julian-klode** [comment]
500 is the server error code. Run with -o debug:: acquire::http=1 to see the messages being exchanged

**Comment by DonFlymoor** [comment]
Ok, this shows something about a proxy (which Sophos uses to control certain things)
```bash
0% [Working]GET /ubuntu-ports/dists/focal/InRelease HTTP/1.1
Host: ports.ubuntu.com
Cache-Control: max-age=0
Accept: text/*
User-Agent: Debian APT-HTTP/1.3 (2.0.2ubuntu0.1) non-interactive


Answer for: http://ports.ubuntu.com/ubuntu-ports/dists/focal/InRelease
HTTP/1.1 500 Software caused connection abort
Date: Fri, 16 Oct 2020 13:57:41 GMT
Cache-Control: no-cache
Pragma: no-cache
Content-Type: text/html; charset="UTF-8"
Content-Length: 0
Via: HTTP/1.1 forward.http.proxy:3128
Connection: close

Err:1 http://ports.ubuntu.com/ubuntu-ports focal InRelease
  500  Software caused connection abort [IP: 91.189.88.152 80]
Reading package lists... Done
Building dependency tree
Reading state information... Done
All packages are up to date.
W: Failed to fetch http://ports.ubuntu.com/ubuntu-ports/dists/focal/InRelease  500  Software caused connection abort [IP: 91.189.88.152 80]
W: Some index files failed to download. They have been ignored, or old ones used instead.
```

**Comment by julian-klode** [comment]
Well, I guess you wanna run wireshark or something now and analyse the traffic and read the code until you figure out what's going on. We can't do much on our side, as we don't see the bug. Also try groovy, it's got some rewritten http code.

**Comment by julian-klode** [comment]
You're currently on Ubuntu focal, you could try groovy.

**Comment by DonFlymoor** [comment]
Ah. I don't think groovy is out for the Rbpi. yet. I may try it sometime.

**Comment by DonFlymoor** [comment]
Upon further investigation, apt is connecting to port 443 for some reason. The proxy, not finding port 443, responds with the 500 error. This may be resolvable if the port is forced to be 80, instead of 443.

**Comment by DonFlymoor** [comment]
Nope. That doesn't fix it.
Here is the captured conversation from wget:
```bash
GET /ubuntu-ports/dists/focal/InRelease HTTP/1.1
User-Agent: Wget/1.20.3 (linux-gnu)
Accept: */*
Accept-Encoding: identity
Host: ports.ubuntu.com
Connection: Keep-Alive

HTTP/1.1 200 OK
Date: Tue, 20 Oct 2020 14:15:53 GMT
Server: Apache/2.4.29 (Ubuntu)
Last-Modified: Thu, 23 Apr 2020 17:34:17 GMT
ETag: "40abc-5a3f8a877d7a3"
Accept-Ranges: none
Content-Length: 264892
Keep-Alive: timeout=5, max=100
Via: HTTP/1.1 forward.http.proxy:3128
Connection: keep-alive
```
Results: File downloads

And the conversation from Apt:
```bash
GET /ubuntu-ports/dists/focal/InRelease HTTP/1.1
Host: ports.ubuntu.com:80
Cache-Control: max-age=0
Accept: text/*
User-Agent: Debian APT-HTTP/1.3 (2.0.2ubuntu0.1) non-interactive

HTTP/1.1 500 Software caused connection abort
Date: Tue, 20 Oct 2020 14:18:44 GMT
Cache-Control: no-cache
Pragma: no-cache
Content-Type: text/html; charset="UTF-8"
Content-Length: 0
Via: HTTP/1.1 forward.http.proxy:3128
Connection: close
```

Telnet doesn't work to get the file either.

**Comment by DonFlymoor** [comment]
Ok. I figured it out. It can't use the User-Agent field. These are the results from telnet:
```bash
$ telnet ports.ubuntu.com 80
Trying 91.189.88.142...
Connected to ports.ubuntu.com.
Escape character is '^]'.
GET /ubuntu-ports/dists/focal/InRelease HTTP/1.1
Host: ports.ubuntu.com:80
Cache-Control: max-age=0
Accept: text/*
User-Agent: Debian APT-HTTP/1.3 (2.0.2ubuntu0.1) non-interactive

HTTP/1.1 500 Software caused connection abort
Date: Tue, 20 Oct 2020 15:52:00 GMT
Cache-Control: no-cache
Pragma: no-cache
Content-Type: text/html; charset="UTF-8"
Content-Length: 0
Via: HTTP/1.1 forward.http.proxy:3128
Connection: close
```

Then without the User-Agent:

```bash
$ telnet ports.ubuntu.com 80
Trying 91.189.88.142...
Connected to ports.ubuntu.com.
Escape character is '^]'.
GET /ubuntu-ports/dists/focal/InRelease HTTP/1.1
Host: ports.ubuntu.com:80
Cache-Control: max-age=0
Accept: text/*
```

And the file is printed to the console

**Comment by julian-klode** [comment]
OK, so your proxy is specifically rejecting APT, there's not much we can do about that. You'll have to set the `Acquire::http::User-Agent` option to something it accepts or get the proxy fixed.

I mean sure, we could look at the specific error and then play cat and mouse with Sophos when they block our alternate user agents.

**Comment by julian-klode** [comment]
Oh, user-agent without `non-interactive` fails too, right?

**Comment by setharnold** [comment]
If you contact Sophos about this, it might be nice to ask them to change the 500 error message to include *some* mention of Sophos in the error message, that would have saved a lot of frustrating debugging.

Thanks

**Comment by DonFlymoor** [comment]
Ok, what it doesn't like is the `-` in `APT-HTTP/1.3` I don't know why, but if I set `Acquire::http::User-Agent='Debian APTHTTP/1.3 (2.0.2ubuntu0.1) non-interactive'` as opposed to `Acquire::http::User-Agent='Debian APT-HTTP/1.3 (2.0.2ubuntu0.1) non-interactive'` it works. So for now, I'll set Acquire::http::User-Agent to 'Debian APTHTTP/1.3 (2.0.2ubuntu0.1) non-interactive' in apt config.

**Comment by julian-klode** [comment]
My assumption would be they block the string APT-HTTP then?

**Comment by julian-klode** [comment]
Please contact Sophos or your people that run the Sophos product such that they can fix that up, I don't have any contact with them.

**Comment by DonFlymoor** [comment]
Sophos does not really care about non-paying customers. Luckily, I was able to manually set the User-Agent in the a config file like so:
`Acquire::http::User-Agent "Debian APTHTTP/1.3 (2.0.2ubuntu0.1) non-interactive";`
And all http sites work to update from and download packages from.
