### ISSUE TITLE
Viewer for pkgcache.bin and srcpkgcache.bin

### ISSUE THREAD

**Issue by eriksank** [Debian/apt#17]
By tracking filesystem changes, I came to the conclusion that the `apt-get update` command reads the files `sources.list` and its extension files in `sources.list.d` in order to update in `/var/cache/apt` the files `pkgcache.bin` and `srcpkgcache.bin`.

I was interested in looking what it would change to these files, but since they are not textual (they are of a binary nature), it requires a custom viewer program to do that.

What does the apt team use during testing to double-check their content? How do you read and visualize these files?

What format do they have? I also did not see any unit tests in the `test` folder of this repository, expressing invariants about these files. What invariants govern these files?

None of these seems to be documented in any way, but more ominously, none of this seems to be actually unit tested either.

Of course, I could try to figure out the giant ball of mud in the source code, to reverse engineer all of this, but anybody who ever does any programming work or even does any testing, would have to do that too. Therefore, there must already be a reusable way of achieving that.

Otherwise, the software would simply be unmaintainable.

How do you go about reading/writing to these files, without making any references to the apt system itself?

**Comment by julian-klode** [comment]
The file is a binary cache file, consisting of various structs defined in apt-pkg/pkgcache.h. It's just a huge file mmapped() into the address space and then directly accessed using structs.

We do not test the cache file format, but all of the tests do make use of caches, whether in-memory or on-disk.

The cache file is for internal use only and not supposed to be read by anything else. Its format may change at any point without prior announcement.

I hope that clears thing up.
