### ISSUE TITLE
Copying /var/cache/apt to another machine leads to a corrupt situation

### ISSUE THREAD

**Issue by eriksank** [Debian/apt#22]
Imagine you install a package:

```
# apt-get install trimage
```

It will download the package and its dependencies in `/var/cache/apt` during installation.

When you then copy `/var/cache/apt` to another machine, with the same configuration of sources in /etc/apt, and try to install the same package:

```
# apt-get install trimage
```

You would expect that it would find the package and the dependencies in `/var/cache/apt` and not need to download anything, and just manage to install the package there too.

This is not what happens.

What happens, is that the `apt-get install` will crash complaining loudly about something being wrong. However, you can solve that by doing an `apt-get update` first.

Still, since `apt-get update` will also store its information  `/var/cache/apt`, why is this a requirement? 

I do not want the second machine to access the network in order to do an `apt-get update`. Shouldn't the second installation have all the information that it needs just by reading the existing `/var/cache/apt`?

By the way, I personally suspect that there will be something wrong with the files `pkgcache.bin`, and `srcpkgcache.bin` in `/var/cache/apt` after just copying the folder. However, since these files are essentially undocumented, I cannot verify this ...

**Comment by julian-klode** [comment]
This is not a useful report. We need to know the error messages with which it crashed.

The .bin files contain a mmap()-able set of structs and are different on each architecture. But they should have enough safety information to detect an invalid or incompatible cache file (major/minor versions for format changes, adler32 checksum for the entire cache [since 1.1.10, before: file size]).

In any case, a much better choice is to copy /var/cache/apt/archives.

**Comment by eriksank** [comment]
An example of what goes wrong. I start from a blank debian:jessie image. I make sure to configure the external repository: 
```
# cat /etc/apt/sources.list.d/docker.list 
deb https://apt.dockerproject.org/repo debian-jessie main
```
I put back `/var/cache/apt` from the backup. Everything should be the same now. The docker package(s) came back from the backup too:
```
# ls archives/ | grep docker
docker-engine_1.12.1-0~jessie_amd64.deb
```
We have the same situation in `/etc/apt` and `/var/cache/apt` as before:
```
# apt-get install docker-engine
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package docker-engine
```
It will not work until I do an `apt-get update`. However, I don't want to do an `apt-get update` because that will possible result in a newer version which will then be downloaded instead of just installing. I could use `--no-download`, and that may work too, but I do not want to access the network at all, not even for an `apt-get update`.

It seems very hard to do a reproducible build of the same server, without accessing the network. Putting back a complete disk image is also not an option, because the server comes preinstalled with an operating system. I just access it through ssh. I want to have exactly the same installation with the same packages as on the original server, by restoring the backups of `/etc/apt` and `/var/cache/apt` without ever downloading anything else.

How to do that?

**Comment by julian-klode** [comment]
Ah well, that's fairly obvious then. You did not copy var/lib/apt/. So the cache is considered out of date and rebuild with the lists in the new host.
