### ISSUE TITLE
Each output of command "apt-get dist-upgrade" on new line

### ISSUE THREAD

**Issue by AlejandroColomar** [Debian/apt#25]
The following kills my eyes, and I think everyone's:
```
# apt-get dist-upgrade
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
The following packages were automatically installed and are no longer required:
  firebird2.5-common firebird2.5-common-doc firebird2.5-server-common
  firebird3.0-common firebird3.0-common-doc imagemagick-common libfbclient2
  libfbembed2.5 libmagick++-6.q16-5v5 libtommath1
Use 'apt autoremove' to remove them.
The following packages will be REMOVED:
  libreoffice-sdbc-firebird
The following NEW packages will be installed:
  gir1.2-packagekitglib-1.0 imagemagick-6-common libjxr-tools libjxr0
  libmagick++-6.q16-6v6 libphodav-2.0-0 libphodav-2.0-common libzip4
  python3-pycurl python3-software-properties software-properties-common
  software-properties-gtk sudo unattended-upgrades
The following packages will be upgraded:
  argyll argyll-ref bluez bluez-obexd bsdmainutils cpp-6 cvs distro-info-data
  dkms evolution evolution-common evolution-plugins ffmpeg file
  fonts-opensymbol g++-6 gcc-6 gcc-6-base gcj-6-jre-lib gir1.2-gtk-3.0
  gir1.2-lokdocview-0.1 gir1.2-polkit-1.0 git git-all git-arch git-cvs
  git-daemon-run git-doc git-el git-email git-gui git-man git-mediawiki
  [...]
  spice-client-glib-usb-acl-helper uno-libs3 ure zlib1g
187 upgraded, 14 newly installed, 1 to remove and 0 not upgraded.
Need to get 279 MB of archives.
After this operation, 11.0 MB disk space will be freed.
Do you want to continue? [Y/n]
```
I think `apt-get` should at least have an option to see those lists on a column style (like ls) or even on a new line each item.

**Comment by julian-klode** [comment]
You could use -V

**Comment by 181514912** [comment]
You can list available updates :
`sudo apt-get --just-print upgrade 2>&1 | perl -ne 'if (/Inst\s([\w,\-,\d,\.,~,:,\+]+)\s\[([\w,\-,\d,\.,~,:,\+]+)\]\s\(([\w,\-,\d,\.,~,:,\+]+)\)? /i) {print "PROGRAM: $1 INSTALLED: $2 AVAILABLE: $3\n"}'`

**Comment by julian-klode** [comment]
@181514912 That's insane. It might stop working if output format changes slightly, and it also does not really list all (possible) upgrades, only the ones upgraded by upgrade. It's much nicer to use apt list -u instead.

Anyhow, -V is basically the option to have one line per package (due to it printing version info, and that being fairly useless on a single line). It's not documented anywhere, though, I guess, so that is something to address.

**Comment by julian-klode** [comment]
Normal mode, without -V:

    The following package was automatically installed and is no longer required:
      libtpm-unseal1
    Use 'apt autoremove' to remove it.
    Suggested packages:
      fonts-stix | otf-stix mozplugger libgnomeui-0
    The following NEW packages will be installed:
      firefox
    0 upgraded, 1 newly installed, 0 to remove and 5 not upgraded.

with -V:


    The following package was automatically installed and is no longer required:
       libtpm-unseal1 (1.3.8-2+b1)
    Use 'apt autoremove' to remove it.
    Suggested packages:
       fonts-stix (1.1.1-4)
       | otf-stix
       mozplugger (1.14.5-2)
       libgnomeui-0 (2.24.5-3.1)
    The following NEW packages will be installed:
       firefox (49.0-4)
    0 upgraded, 1 newly installed, 0 to remove and 5 not upgraded.

**Comment by julian-klode** [comment]
Closing since it's unclear if anything is needed given that -V basically does what is asked.
