### ISSUE TITLE
apt install of local debs does not tab-complete

### ISSUE THREAD

**Issue by chipaca** [Debian/apt#28]
this fails:
```
$ touch xyzzy.deb
$ apt install xyzzy<tab>
```
because the completion support for install is using `_filedir` wrong.

**Comment by julian-klode** [comment]
Not again. I told you all this already in the Launchpad bug report, but here we go again: It's working as it should:

(1) Without a leading ./, only package names are used

# apt install xy<tab>
xye xye-data xymon xymon-client xyscan

(2) With ./, only file names are used

# apt install ./x<tab>
xyzzy.deb


Here are the other comments to that bug report there:

> The completion is still wrong anyway: apt only accepts ./package.deb, not package.deb. 
> And it seems to work here as it.

> Actually:
> 
> jak@jak-x230:~/Downloads$ ls *.deb
> AdbeRdr9.5.5-1_i386linux_enu.deb debhelper_9.20160115ubuntu3_all.deb
> jak@jak-x230:~/Downloads$ _filedir "deb"
> jak@jak-x230:~/Downloads$ echo $_
> deb
> jak@jak-x230:~/Downloads$ _filedir "*.deb"
> jak@jak-x230:~/Downloads$ echo $_
> AdbeRdr9.5.5-1_i386linux_enu.deb debhelper_9.20160115ubuntu3_all.deb
> So, it seems you are wrong.

**Comment by chipaca** [comment]
My apologies for not seeing your reply to the bug on launchpad. I saw your request to move the branch here, and did that.

**Comment by chipaca** [comment]
This is the behaviour you have in `apt` right now:
```.sh-session
$ mkdir xyzzz
$ touch xyzzy.deb xyzzx.two.deb
$ apt install xyzz<tab>
xyzzx.two.deb  xyzzz/ 
```

With my change,

```.sh-session
$ apt install xyzz
xyzzx.two.deb  xyzzy.deb      xyzzz/         
```

**Comment by glaubitz** [comment]
@chipaca:

This is by design. You need to prefix packages you install from a file with the prefix "./" as otherwise there wouldn't be a way for apt to differentiate between packages from your filesystem and the repository.

Without the prefix "./", apt assumes that the package name comes from the archive and it tries to resolve the full name using the archive, not any package in the current folder. With the prefix, it assumes it's a file.

**Comment by chipaca** [comment]
@glaubitz see my example above. What you describe is at odds with what it is doing, today. My change makes it consistent in one direction; you can argue about it needing to be consistent in another, but the code as it stands today behaves inconsistently.

**Comment by glaubitz** [comment]
This looks like a bug in apt then. It shouldn't match any files without the "./" prefix for the aforementioned reasons. I'm also not quite sure whether package names like "abc.def.deb" would exist in the real world.

**Comment by chipaca** [comment]
Apparently `AdbeRdr9.5.5-1_i386linux_enu.deb` and `debhelper_9.20160115ubuntu3_all.deb` are real-world examples.

**Comment by glaubitz** [comment]
In any case, the proper fix would be to not make it match any files without the "./" prefix. At least that's why the design intends. I don't really think it makes much sense to start a general discussion about the prefix requirement though. If the apt developers prefer the prefix requirement, they get to make this decision.

**Comment by chipaca** [comment]
Just to be clear, is it only `./` prefix or is it also a `/` prefix?
Where can I read the design you're referring to?

**Comment by chipaca** [comment]
The reason I ask is because a workaround for `./`-prefix is to call `_filedir` with `/*.deb` (making it match `*./*.deb`, which `./` will match but `foo.bar.deb` will not), but making it match absolute paths would require implementing a chunk of `_filedir` over again. It's not a big function tbh, but I thought I'd ask before jfdi and getting shouted at.

**Comment by julian-klode** [comment]
`*./*.deb` will match nothing. Apparently "/*.deb" and "*/*.deb" work, though, but only for the ./ matches, not the absolute paths (I don't understand what you say in your parentheses, though, "*./*.deb" matches zero things - and the other one matches foo.bar.deb of course).

But the whole thing is a minor detail: In practice, you mostly won't be able to use apt install <local deb> completions without a leading ./ or / anyway - there are just too many package names, and those have priority in the completion.

Now, if we can easily work around this, we should do it, but duplicating code from bash-completion seems like overkill to me. That is, some workaround like:

_filedir "*.deb"
<replace relative paths without ./ with ones with ./>

**Comment by chipaca** [comment]
After a good night's sleep it struck me that there was an easy way forwards. Can you reopen the PR (#29), or should I do a new one?

**Comment by chipaca** [comment]
Gah, just realised I pushed to the branch with the PR closed, so github won't pick it up; I'll have to do a new one anyway.
