### ISSUE TITLE
docbook-xsl is not picked up on Arch Linux

### ISSUE THREAD

**Issue by mdeguzis** [Debian/apt#32]
I took over maintainership of the AUR package for apt. `docbook-xsl` is not picked up, presumably due to the installed folder being named `docboox-xsl-<VERSION>`. 

See:  https://www.archlinux.org/packages/extra/any/docbook-xsl/

The pathing should check more openly on Arch Linux if possible. I am manually setting DOCBOOX_XSL with cmake for now.

**Comment by julian-klode** [comment]
Hmm, last time I checked there were some symlinks IIRC. It's definitely a good idea in any case.

**Comment by mdeguzis** [comment]
There are no symlinks in `/usr/share/xml/docbook/`, so I'm not sure where they would be, i'll double check when I get home and work more on the AUR package.

**Comment by mdeguzis** [comment]
Current build log: http://sprunge.us/HXbU

**Comment by mdeguzis** [comment]
A simple approach like that of the PKGBUILD would work fine:

```
ls -d /usr/share/xml/docbook/xsl-stylesheets-* | xargs basename
```

**Comment by julian-klode** [comment]
I'm not a huge fan of that idea. There must be some way for arch packages to know which version of the style sheets is the current one. Every other distribution I know of ships some form of current symlink (including openSUSE, Fedora, and FreeBSD). I'd highly recommend Arch to do the same.

Just choosing one at random seems like a weird idea.

**Comment by mdeguzis** [comment]
You can easily list the right version with pacman, but that isn't distro agnostic of course. I'll check the installed files the package provides. Could be somewhere.

**Comment by mdeguzis** [comment]
It would not be one at random, the [PKGBUILD](https://git.archlinux.org/svntogit/packages.git/tree/trunk/docbook-xsl.install?h=packages/docbook-xsl) removes the old version on install. There can be only one version of docbook-xsl in `/usr/share/xml/docbook/`. Sure you could do a complicated grep of VERSION.xsl, but that is worse that the above suggestion. I'll send out something to the maintainer referencing this.

**Comment by Conan-Kudo** [comment]
@mdeguzis It seems like it would be easier and saner to implement an unversioned symlink on the Arch side. This is the first time I've heard of this kind of problem, and it seems like something broken from Arch rather than the other way around.

**Comment by julian-klode** [comment]
We won't add support for versioned docbook dirs.
