### ISSUE TITLE
'apt-get update' complains that Release file is absent from repository when it is present

### ISSUE THREAD

**Issue by jean-christophe-manciot** [Debian/apt#33]
apt 1.3.3
Ubuntu 16.10 4.8
```
/etc/apt/sources.list.d/jean-christophe-manciot.list:
deb https://gitlab.com/jean-christophe-manciot/ppa/raw/master/Ubuntu yakkety stable #JC Manciot's stable PPA
deb https://gitlab.com/jean-christophe-manciot/ppa/raw/master/Ubuntu yakkety unstable #JC Manciot's unstable PPA

apt update
...
Ign:14 https://gitlab.com/jean-christophe-manciot/ppa/raw/master/Ubuntu yakkety InRelease
Err:15 https://gitlab.com/jean-christophe-manciot/ppa/raw/master/Ubuntu yakkety Release
  404  Not Found
...
E: The repository 'https://gitlab.com/jean-christophe-manciot/ppa/raw/master/Ubuntu yakkety Release' does no longer have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
...
```
Although:
```
https://gitlab.com/jean-christophe-manciot/ppa/raw/master/Ubuntu/dists/yakkety/Release
Architectures: amd64
Codename: yakkety
Components: stable unstable
Date: Mon, 19 Dec 2016 12:06:49 +0000
Description: Latest Ubuntu 16.10 packages
Label: Ubuntu 16.10 PPA
Origin: Jean-Christophe Manciot
Suite: yakkety
Version: 16.10
MD5Sum:
...
SHA1:
...
SHA256:
...
SHA512:
...
```

**Comment by julian-klode** [comment]
It really does not exist here:

$ curl -I https://gitlab.com/jean-christophe-manciot/ppa/raw/master/Ubuntu/dists/yakkety/Release
HTTP/1.0 200 Connection established
HTTP/1.1 404 Not Found

**Comment by jean-christophe-manciot** [comment]
I have the same error:
```
curl -I https://gitlab.com/jean-christophe-manciot/ppa/raw/master/Ubuntu/dists/yakkety/Release
HTTP/1.1 404 Not Found
```
How can I access the file with chrome browser & not with curl?

**Comment by julian-klode** [comment]
Maybe the repo is private and you have the cookies for it in Chrome? I don't see any activity in the repo, so I assume it's either empty or private.

**Comment by jean-christophe-manciot** [comment]
Due to a current issue with GitLab's way of managing git repository storage, I had to switch my original PPA repo to a new one: the original PPA has been emptied & renamed as https://gitlab.com/jean-christophe-manciot/old_ppa, and the new one has kept the original URL https://gitlab.com/jean-christophe-manciot/ppa.
It seems that Chrome is able to point to the real URL, but curl cannot somehow.
The new PPA is **public** & all files have already been pushed:
![public](https://cloud.githubusercontent.com/assets/13176858/21313807/3e948140-c5f4-11e6-88ba-1914382b98bf.jpg)
![yakkety](https://cloud.githubusercontent.com/assets/13176858/21313890/8cd8ebca-c5f4-11e6-8702-e85f3d11286e.jpg)
![ppa](https://cloud.githubusercontent.com/assets/13176858/21313902/92d7ab56-c5f4-11e6-96d4-82f4fe841629.jpg)
The previous PPA contains only the README.md file:
![old_ppa](https://cloud.githubusercontent.com/assets/13176858/21313985/f043812a-c5f4-11e6-9cd4-98c7dd99888b.jpg)

**Comment by jean-christophe-manciot** [comment]
Maybe it's just a DNS TTL issue, but I don't get how chrome gets it right and not curl.

**Comment by julian-klode** [comment]
It definitely is not public at some level.

![screenshot from 2016-12-19 15-06-48](https://cloud.githubusercontent.com/assets/6325588/21315580/28b5c466-c5fd-11e6-8b87-7fce7a7951a7.png)

![screenshot from 2016-12-19 15-06-43](https://cloud.githubusercontent.com/assets/6325588/21315585/2e44f712-c5fd-11e6-9c3b-18e472d977a9.png)


Anyway, this is not gitlab user support, so I'm closing the issue.

**Comment by jean-christophe-manciot** [comment]
It does not seem to be a gitlab issue, but rather a DNS TTL which has not expired yet for some DNS providers or some cache issue somewhere: your screenshots seem outdated because there are no such pages right now on the site; you would get an error message if the PPA was private.
Could you please try with google DNS providers 8.8.8.8 or 8.8.4.4?

**Comment by julian-klode** [comment]
Hey, it's your issue. It's not a DNS issue either, that would be weird (it's 104.210.2.228 on my DNS and Google DNS). Go talk to gitlab support and figure the issue out with them, it's definitely not on our side.
