### ISSUE TITLE
Better explain why signature is invalid

### ISSUE THREAD

**Issue by LynxChaus** [Debian/apt#35]
After https://github.com/Debian/apt/commit/33d7a8d672c8c720947e81158de4a5a07be05b72 apt just report "signatures were invalid" without explain why.

Make more informative message.

**Comment by julian-klode** [comment]
Yes, we really should do that. That also delays rolling that out to the stable 1.3 and 1.2 branches (which were originally scheduled to shut down SHA1 in January).

**Comment by julian-klode** [comment]
I think we're just going to live with it as is now, it's not worth it anymore.
