### ISSUE TITLE
Apt crashes on attempt to copy text

### ISSUE THREAD

**Issue by ACinnamonUserInUK** [Debian/apt#36]
**What happened**

- `sudo apt update && sudo apt upgrade`
- I received a message about an upgrade being set to overwrite a configuration file. I took up the option to compare the two versions of that file. I used the 'q' key to exit the comparison. Then, within the same terminal, I selected and tried to copy - with ctrl-C, I think - the name of the file at issue.
- Result: apt spewed some text and threw and error and I had to run ` dpkg --configure -a` (as Apt did helpfully tell me) to fix things.

Screenshot: 

![image](https://cloud.githubusercontent.com/assets/9998846/23694132/08888046-03d0-11e7-9ba8-fa18fbde188f.png)

**What should have happened**

The text should have been copied to the clipboard or, at worst, nothing should have happened.

**My system**

OS: Linux Mint 18.1 xenial x86_64 
Kernel: 4.8.0-41-generic 
Shell: /bin/bash 
Resolution: 1280x800 
DE: Cinnamon 
WM: Mutter (Muffin) 
CPU: Intel 2 Duo T7500 (2) @ 2.2GHz 
GPU: Intel Integrated Graphics 
Memory: 2235MB / 7973MB 

If I am reporting this bug to the wrong place, then please direct me to the right place. Thank you.

**Comment by julian-klode** [comment]
Ctrl-C sends an interrupt, it doesn't copy text. And it's your own Python script called apt that's stopping here, not the official apt binary.

**Comment by ACinnamonUserInUK** [comment]
Julian-Klode: good points. I realised the point about the interrupt shortly after posting the report; as to apt the binary and apt the python script - I was unsure about just which program was at issue.

**Comment by ACinnamonUserInUK** [comment]
I am adding to this page because it seems to me that **even just scrolling in my terminal window produces strange results** - namely, a load of odd characters to appear - when confronted by the aforementioned, sometimes rather critical 'keep local version?' window.

_I appreciate that I may be reporting this problem on the wrong bugtracker_. ('it's your own Python script called apt that's stopping here, not the official apt binary.') Yet, and as I said in my first post, if this is the wrong place, _please tell me the right place_. I have tried to locate the right bugtracker myself, but to no avail.

Thank you for your time.
