### ISSUE TITLE
Line ending issue when "Reading database"

### ISSUE THREAD

**Issue by craigfrancis** [Debian/apt#37]
When running `apt-get upgrade` via a cron job, there is a "Reading database" section.

In the email this appears as:

    (Reading database ...
    (Reading database ... 5%
    (Reading database ... 10%
    (Reading database ... 15%
    (Reading database ... 20%

Where does this come from? as the first "Reading database" line ends with a "\r".

Not a major issue, but this does break DKIM signing of emails.

---

It looks like it might be related to:
https://github.com/Debian/apt/blob/master/apt-pkg/contrib/progress.cc

---

In Gmail this will result in the header `dkim=neutral (body hash did not verify)`.

If you're using OpenDKIM, you can avoid this by setting `FixCRLF yes`... but it would be nice to fix the cause of the problem (especially as it only happens once).

**Comment by julian-klode** [comment]
These progress messages come from dpkg.

**Comment by julian-klode** [comment]
Note that you should pass -q when running from a non-interactive script.

**Comment by craigfrancis** [comment]
Thanks Julian,

And yes, I probably should use `-q` for non-interactive tasks... I've come from using `yum`, and it's quiet mode causes it to `Run without output`.
