### ISSUE TITLE
apt-get update doesnt check for new Packages.gz

### ISSUE THREAD

**Issue by wyllys66** [Debian/apt#39]
Package info:  apt 1.2.15ubuntu0.2 in Ubuntu 16.04.1 LTS

I have a local repository setup and when I add new packages to it (or update an existing one) we update the Packages.gz file using "dpkg-scanpackages . /dev/null | gzip -9c > Packages.gz" to make sure that the Package.gz is up to date. When we then run "apt-get update" to update the package indexes.  However, it never looks for the Packages.gz file and so we cannot install updated packages since they are not recognized as being updated.

Is this something new with apt 1.2.X?  We didnt have this problem in Trusty with apt-1.0.1ubuntu2.13.  I've googled around and havent seen any reference to this particular problem.  Is there a different file that we need to update in order to have it be recognized when clients run "apt-get update" ?

**Comment by julian-klode** [comment]
If the date of the release file has not changed, apt does not download anything

**Comment by wyllys66** [comment]
Is that something new?  We didnt need to do anything with the Release file in earlier versions.

**Comment by wyllys66** [comment]
I see our problem, we didnt used to have a Release file at all, but lately we added one and that's why its causing a problem.  Removing the "Release" file causes 'apt-get update' to fetch the Packages.gz file and update things correctly. 

Thanks for the help!

**Comment by julian-klode** [comment]
I'd really add a Release file though, especially if you access it via http. Not having one means (1) more load on servers and (2) makes apt progress even weirder than it can be with a release file.

**Comment by wyllys66** [comment]
Load isnt an issue in our environment, its rarely used.  We often update just a single package in the repo, would we also have to bump a version number or something in the Release file in order to get it to update correctly?  Just "touch"-ing the Release file to update the date did not solve the problem.

**Comment by julian-klode** [comment]
There usually is a Date field inside the Release file. That's what apt is looking at.

**Comment by wyllys66** [comment]
ok, thanks.
