### ISSUE TITLE
[1.4.3] dh_missing: unknown option sourcedir

### ISSUE THREAD

**Issue by jean-christophe-manciot** [Debian/apt#41]
On Ubuntu 16.10
debhelper 10.3
tag: 1.4.3

Building with:
```
dpkg-buildpackage --build=binary -m"Jean-Christophe Manciot <manciot.jeanchristophe@gmail.com>"
```
leads to:
```
...
dh_install -papt-utils -X/dump
dh_install -papt -Xmethods/https
dh_install --remaining --list-missing
dh_install: Please use dh_missing --list-missing/--fail-missing instead
dh_install: This feature will be removed in compat 11.
Use of uninitialized value $options[1] in system at /usr/bin/dh_install line 276.
Unknown option: sourcedir
dh_missing: unknown option; aborting
debian/rules:24: recipe for target 'override_dh_install-arch' failed
```
**No such issue with 1.4.2**.

**Comment by julian-klode** [comment]
There was no change there in 1.4.3

**Comment by jean-christophe-manciot** [comment]
After further investigation, I'm starting to think that it seems to be a debhelper issue since I don't see any sourcedir option in your scripts.
The 10.3 release is quite new.

**Comment by jean-christophe-manciot** [comment]
What debhelper release are you using?

**Comment by jean-christophe-manciot** [comment]
I'm able to build apt with debhelper 10.2.5.

**Comment by julian-klode** [comment]
Well, that's what you get for building with experimental versions of debhelper.

**Comment by julian-klode** [comment]
See https://anonscm.debian.org/git/debhelper/debhelper.git/commit/?id=7dd8f2c09a949c0318fd2b9ea5419f671c921088

**Comment by jean-christophe-manciot** [comment]
Thanks for the link.
