### ISSUE TITLE
apt-cdrom removable device detection broken

### ISSUE THREAD

**Issue by youjinbou** [Debian/apt#48]
When having several removable drives installed (cdroms), apt-cdrom fails to notice them and insists on using a single drive.

The issue is located in 'apt-pkg/cdrom.cc', in the 'pkgUdevCdromDevices::Dlopen' method, where the location of the udev dll is pointing to 'libudev.so.0' instead of whichever lib is currently installed on the system. The latest debian release uses 'libudev.so.1', which seemingly has the same API, thus simply patching the string to the correct name fixes the issue. 
However, I wonder whether a different approach would avoid this bug to occur again at the next major revision of libudev (or if the apt tools need to be used on a platform using another libudev version?). Btw, what's the rational of using a dlopen, instead of simply relying on ld? Is this a package dependency issue?

**Comment by mvo5** [comment]
Thanks for raising this issue! It sounds like we need to indeed bump to use libudev.so.1 in the short term.

As for why dlopen() - there are a couple of reasons, the most important one is that some platforms that we support (like kfreebsd, gnu/hurd) do not have udev at all.

**Comment by julian-klode** [comment]
I think there's no real need to dlopen(), I just made it link normally now and add a [linux-any] build-dep on libudev. This means we get proper handling for ABI breaks.

**Comment by julian-klode** [comment]
Was closed in https://github.com/Debian/apt/commit/96b4580561cd2a8d1467143d67d2a612f0ddc75a
