### ISSUE TITLE
apt-key del always return OK

### ISSUE THREAD

**Issue by albuic** [Debian/apt#49]
"apt-key del <random>" always return OK even if the key does not exist or the string is not a key.
It should return Key Not Found or NOT OK

**Comment by julian-klode** [comment]
That's probably right, but changing it now might break stuff. And given that the major (well hopefully only) use of it is to migrate away from apt-key to a file in trusted.gpg.d, and that apt-key is essentially deprecated, that seems like not worth the breakage.
