### ISSUE TITLE
Operation Remv, Kept, Upgr, New

### ISSUE THREAD

**Issue by lasers** [Debian/apt#51]
Hi there. I hope I'm in a right place. I'm playing around a bit with `apt-get dist-upgrade --dry-run -V`,  https://pastebin.com/raw/TZam9XnY, for scripting purposes.
```
The following packages were automatically installed and are no longer required:
   kde-style-qtcurve-qt4 (1.8.18+git20160112-0cd6aae-1)
   libkf5purposewidgets5 (1.1-1~+16.04+xenial+build32)
   libpcre16-3 (2:8.38-3.1)
   libqt5clucene5 (5.7.1-2+16.04+build13)
   libqtcurve-utils2 (1.8.18+git20160112-0cd6aae-1)
```
After reading the man page: http://manpages.ubuntu.com/manpages/zesty/man8/apt-get.8.html,
```
   Simulated runs print out a series of lines, each representing a
   dpkg operation: configure (Conf), remove (Remv) or unpack (Inst).
   Square brackets indicate broken packages, and empty square brackets
   indicate breaks that are of no consequence (rare).
```
I'm wondering about `remove (Remv)` lines. I didn't get any. This is a bit more than 600 packages. Is it a bug or something else? I think I'm expecting at least 5 `Remv` lines.

Thoughts on the new options such as `(Kept)` to print lines of the following packages that have been kept back... and `(Upgr)` to print lines of the following packages that will be upgraded? And also... I can't confirm this, but I think `(New)` too to print lines of the following NEW packages that will be installed.

I asked because all of that information are shown right before the `CONF` and `INST` lines. If it's not possible (due to dpkg or such), is there a different way to get them? Thank you.

**Comment by lasers** [comment]
(Nit).
```
The following packages have unmet dependencies:
 libpython3.5-stdlib : Depends: libpython3.5-minimal (= 3.5.2-2ubuntu0~16.04.3) but 3.5.2-2~16.01 is installed
 python3.5 : Depends: python3.5-minimal (= 3.5.2-2ubuntu0~16.04.3) but 3.5.2-2~16.01 is installed
E: Unmet dependencies. Try using -f.
```
```
The following packages will be upgraded:
   libpython3.5-minimal (3.5.2-2~16.01 => 3.5.2-2ubuntu0~16.04.3)
   python3.5-minimal (3.5.2-2~16.01 => 3.5.2-2ubuntu0~16.04.3)
2 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

I wonder if we should align this up with others?
```
 libpython3.5-stdlib : Depends: libpython3.5-minimal (= 3.5.2-2ubuntu0~16.04.3) but 3.5.2-2~16.01 is installed
 python3.5 : Depends: python3.5-minimal (= 3.5.2-2ubuntu0~16.04.3) but 3.5.2-2~16.01 is installed
```
The difference is two missing spaces. I'm aware it's not same as others.

**Comment by julian-klode** [comment]
OK, so the 5 packages in the initial post _can_ be automatically removed, but they are not. You'd have to run autoremove.

As for adding Kept, New and Upgr - that makes no sense. The output lists dpkg operations performed. Keeping back is not a dpkg operation, it's nothing that needs to be simulated. For New and Upgr, the fields are useless, the information is already in Inst:

```
Inst docker-containerd (0.2.3+git+docker1.13.1~ds1-1 Debian:unstable [amd64])                
Inst docker.io [1.13.1~ds1-2] (1.13.1~ds2-3 Debian:unstable [amd64])                      
```

Here, docker.io has the old version in brackets, and docker-containerd does not -> new install.

Comment #2 about spacing is an entirely different topic altogether, unrelated to this issue, so you might want to open a new one.

**Comment by julian-klode** [comment]
Note that we do not really track bugs here as much as in the Debian bug tracker, or Launchpad.

**Comment by julian-klode** [comment]
Or well, less eyes look on it. The others have a lot of bug reports so some stuff might get lost.
