### ISSUE TITLE
Failed to fetch http://ppa.launchpad.net/rwky/redis/ubuntu/dists/trusty/main/binary-amd64/Packages  403  Forbidden

### ISSUE THREAD

**Issue by Salman888** [Debian/apt#55]
RUN apt-get update && apt-get install -yqq mysql-server-5.5 libmysqlclient18 libmysqlclient-dev
---> Running in f96a3d8a7d38
Ign http://archive.ubuntu.com trusty InRelease
Get:1 http://archive.ubuntu.com trusty-updates InRelease [65.9 kB]
Get:2 http://archive.ubuntu.com trusty-security InRelease [65.9 kB]
Get:3 http://ppa.launchpad.net trusty InRelease [20.8 kB]
Ign http://ppa.launchpad.net trusty InRelease
Ign http://ppa.launchpad.net trusty InRelease
Get:4 http://archive.ubuntu.com trusty Release.gpg [933 B]
Get:5 http://ppa.launchpad.net trusty Release.gpg [316 B]
Get:6 http://archive.ubuntu.com trusty Release [58.5 kB]
Ign http://ppa.launchpad.net trusty Release.gpg
Get:7 http://ppa.launchpad.net trusty Release [15.1 kB]
Ign http://ppa.launchpad.net trusty Release
Get:8 http://archive.ubuntu.com trusty-updates/main Sources [409 kB]
Err http://ppa.launchpad.net trusty/main amd64 Packages

Err http://ppa.launchpad.net trusty/main amd64 Packages

Err http://ppa.launchpad.net trusty/main amd64 Packages

Get:9 http://archive.ubuntu.com trusty-updates/restricted Sources [6322 B]
Err http://ppa.launchpad.net trusty/main amd64 Packages

Get:10 http://archive.ubuntu.com trusty-updates/universe Sources [195 kB]
Err http://ppa.launchpad.net trusty/main amd64 Packages
403 Forbidden
Get:11 http://archive.ubuntu.com trusty-updates/main amd64 Packages [1043 kB]
Get:12 http://ppa.launchpad.net trusty/main amd64 Packages [7796 B]
Get:13 http://archive.ubuntu.com trusty-updates/restricted amd64 Packages [17.2 kB]
Get:14 http://ppa.launchpad.net trusty/main amd64 Packages [756 B]
Get:15 http://archive.ubuntu.com trusty-updates/universe amd64 Packages [436 kB]
Get:16 http://archive.ubuntu.com trusty-security/main Sources [147 kB]
Get:17 http://archive.ubuntu.com trusty-security/restricted Sources [4931 B]
Get:18 http://archive.ubuntu.com trusty-security/universe Sources [67.2 kB]
Get:19 http://archive.ubuntu.com trusty-security/multiverse Sources [3195 B]
Get:20 http://archive.ubuntu.com trusty-security/main amd64 Packages [696 kB]
Get:21 http://archive.ubuntu.com trusty-security/restricted amd64 Packages [14.1 kB]
Get:22 http://archive.ubuntu.com trusty-security/universe amd64 Packages [198 kB]
Get:23 http://archive.ubuntu.com trusty-security/multiverse amd64 Packages [4795 B]
Get:24 http://archive.ubuntu.com trusty/main Sources [1064 kB]
Get:25 https://oss-binaries.phusionpassenger.com trusty InRelease
Ign https://oss-binaries.phusionpassenger.com trusty InRelease
Get:26 http://archive.ubuntu.com trusty/restricted Sources [5433 B]
Get:27 http://archive.ubuntu.com trusty/universe Sources [6399 kB]
Get:28 https://oss-binaries.phusionpassenger.com trusty Release
Get:29 https://oss-binaries.phusionpassenger.com trusty/main amd64 Packages
Get:30 http://archive.ubuntu.com trusty/main amd64 Packages [1350 kB]
Get:31 http://archive.ubuntu.com trusty/restricted amd64 Packages [13.0 kB]
Get:32 http://archive.ubuntu.com trusty/universe amd64 Packages [5859 kB]
Fetched 18.3 MB in 5s (3208 kB/s)
W: Failed to fetch http://ppa.launchpad.net/rwky/redis/ubuntu/dists/trusty/main/binary-amd64/Packages 403 Forbidden

E: Some index files failed to download. They have been ignored, or old ones used instead.
2017/12/11 10:15:07 The command [/bin/sh -c apt-get update && apt-get install -yqq mysql-server-5.5 libmysqlclient18 libmysqlclient-dev] returned a non-zero code: 100

**Comment by julian-klode** [comment]
No such PPA exists.
