### ISSUE TITLE
zh_CN.po中第465行的有个单位“个”多余了

### ISSUE THREAD

**Issue by caozuohua** [Debian/apt#57]
由apt-pkg/acquire.cc中1333行大概可以看出，"Retrieving file %li of %li (%s remaining)"中remaining的应该是一个表时间的（其本身有单位”秒“），所以zh_CN.po中关于这个msgid的翻译不应该有“个” ：
    (还剩 %s 个) -> (还剩 %s )

**Comment by julian-klode** [comment]
I'm not sure what that means. If you have a problem with the translation, please contact the translator listed in the file.Thank you.
