### ISSUE TITLE
Cli interface warning 

### ISSUE THREAD

**Issue by fumseck** [Debian/apt#62]
Good afternoon

Why i've **apt does not have a stable CLI interface use with caution in shell script** ? it's new !

It's **dangerous** to use in **shell scripts** and not in command line or **simply it's not stable** ?

In hope to know how to **suppress this warning** and of course to know if it's **dangerous to users**.

**Comment by egormanga** [comment]
**Apt** is more made for users, not for scripts, and it's interface may vary from version to version. You should use **apt-get** in scripts, which has a stable CLI interface.

**Comment by fumseck** [comment]
ok thanks
