### ISSUE TITLE
Nvidia Cuda 9.1 support for debian stretch

### ISSUE THREAD

**Issue by eeerrrttty** [Debian/apt#63]
Sorry if im wrong, but appears that debian can only get until version 375 of nvidia drivers, cuda 9.1 requires the version 390+.

Its very important for users that mine cryptocoins using GPU's.
Im having many troubles with the drivers, after having at least 3 fresh S.O install i had to install timeshift to manage the packages that were broken after some try to upgrade the drivers.

please, some light in that.
sorry if bad english

**Comment by julian-klode** [comment]
384 is available in backports, and 390 should follow eventually I guess. Ask the debian backports mailing list, this is a seconary bug tracker for the package manager apt.
