### ISSUE TITLE
Missing tagfile-keys.h in apt-1.4.8 installation

### ISSUE THREAD

**Issue by namon123x** [Debian/apt#68]
Hi,

I was trying to install the apt-1.4.8. The process of "CMake" is successfully done,
as the proof of final line "-- Build files have been written to: /short/fb81/jh8413/apt-1.4.8"

However, the problem happens when I am trying to "make all install"

[  4%] Building CXX object apt-pkg/CMakeFiles/apt-pkg.dir/deb/deblistparser.cc.o
/short/fb81/jh8413/apt-1.4.8/apt-pkg/deb/deblistparser.cc:26:34: fatal error: apt-pkg/tagfile-keys.h: No such file or directory
 #include <apt-pkg/tagfile-keys.h>

As you can, the script of deblistparser.cc.o fails to call the "include <apt-pkg/tagfile-keys.h>",
because of the non-existing file.
I seach the files under the directory of apt-pkg:
ls apt-pkg/tagfile*

It shows:
apt-pkg/tagfile-compat.cc  apt-pkg/tagfile-order.c  apt-pkg/tagfile.h
apt-pkg/tagfile-keys.list  apt-pkg/tagfile.cc

None of the files is tagfile-keys.h
I looked into different versions of apt, but still cannot find this file.
May you advice where can I download it?
Thank you so much.

**Comment by julian-klode** [comment]
It's generated at build time from tagfile-keys.list  not sure whwts going on here.

**Comment by namon123x** [comment]
Thanks for your replies. Is it possible for you to share a file of tagfile-keys.h with me?
Or I will try to post all the log to figure out which process of build fails...
Thanks

**Comment by julian-klode** [comment]
It's generated when running cmake. It's a tiny perl script that is executed. I might have forgotten to add error checking to the call. Make sure to build outside of the source tree in a clean build tree, and check the entire output of cmake - there should be an error message somewhere.

**Comment by julian-klode** [comment]
Generally yes, you need dpkg (or manually define DPKG_DATADIR and COMMON_ARCH variables) but that error is from a different invocation, namely the one defining DPKG_DATADIR.

**Comment by drzacek** [comment]
Which script exactly should generate tagile-keys.h? I'm having same problem, nothing relevant in CMakeError.log.

**Comment by julian-klode** [comment]
triehash

**Comment by King-1025** [comment]
How to fix it?

**Comment by King-1025** [comment]
This similar error occurred in my compilation. How to fix it?

**Comment by King-1025** [comment]
It's similar that one error is in my compilation.How to fix it?

**Comment by King-1025** [comment]
It's similar that one error is in my compilation.How to fix it?
Great Lord!
