### ISSUE TITLE
Compile failure po4a: not found

### ISSUE THREAD

**Issue by kamen94** [Debian/apt#70]
$ make
    ...............
    [ 10%] Generating de/apt.ent (or dropping it)
    /bin/sh: 1: po4a: not found
    doc/CMakeFiles/libapt-pkg-doc.dir/build.make:1428: recipe for target 'doc/de/apt.ent.po4a-stamp' failed
    make[2]: *** [doc/de/apt.ent.po4a-stamp] Error 127
    CMakeFiles/Makefile2:1011: recipe for target 'doc/CMakeFiles/libapt-pkg-doc.dir/all' failed
    make[1]: *** [doc/CMakeFiles/libapt-pkg-doc.dir/all] Error 2
    Makefile:140: recipe for target 'all' failed
    make: *** [all] Error 2
deabin version buster/sid
use deabin on Windows Subsystem Linux

**Comment by julian-klode** [comment]
Well, install it...

**Comment by kamen94** [comment]
Sorrry,But I did not any package named po4a by using apt.
So,How do I install this package?

**Comment by kamen94** [comment]
emmmmmm, The reason why I didn't any package named po4a was that I didn't include Universe components in source.list . Too bad
