### ISSUE TITLE
autoremove: different handling of reverse dependencies when alternatives are listed

### ISSUE THREAD

**Issue by kmotavalli** [Debian/apt#71]
Sometimes installing a package, say Z, removing it and then running autoremove does not result in all automatically installed packages being removed.

This happens because one of the automatically-installed packages, P, is also listed as a dependency, a recommends or a suggests of some other package, let's call it A, installed on the system in a transaction which bears no relation with Z.

APT, when evaluating reverse dependencies of autoremoval candidate packages, can be made to ignore Suggests, but another issue exists:

let's say A lists P as a depedency. 
A also lists C, F, G as possible alternatives to the P package dependency, this way:
C|P|F|G

F is also installed on the system. If I got it right, APT will not mark P for autoremoval because it's listed as a dependency of A.

If that's the case, the suggestion would be to look into improving APT so that when the package being considered for autoremoval is listed as a dependency of some other package along with other alternatives, one or more of which is already installed to satisfy the dependency, APT proceeds with marking the package as boring for autoremoval.

Does it make sense, even as an option?

**Comment by julian-klode** [comment]
I'm not sure it's a good result in the generic case: e.g. you install X that depends on A|B, and Y that depends on B|A, you usually do want both A and B, as Y works best with B and X with A.

It's also bad to implement optimally. I do have a Python script that can minimize the system down to the minimum amount of packages needed to keep the manually installed packages installed at https://salsa.debian.org/jak/cleanup - you might want to try that.

I expect we'll see this eventually as part of a different solver (https://salsa.debian.org/apt-team/apt-solver-kalel), but it's not worth IMO keeping a bug open, especially here where there is fairly limited interaction from our side.
