### ISSUE TITLE
Can this repo be mirroring salsa?

### ISSUE THREAD

**Issue by muru** [Debian/apt#74]
Now that the Debian git repos have moved, can this mirror be updated to point to it?

**Comment by julian-klode** [comment]
We'd love to, but no idea how

**Comment by paultag** [comment]
The mirror feature is setup by GitHub support - just email GitHub support,
they can fix it

**Comment by muru** [comment]
The [Github docs](https://help.github.com/articles/about-github-mirrors/) say:

> To set up your own mirror, you can configure [a post-receive hook](https://git-scm.com/book/en/v2/Customizing-Git-Git-Hooks) on your official project repository to automatically push commits to a mirror repository on GitHub.com (or GitHub Enterprise).

And Gitlab should support this. Over on Gitlab.com:

![Imgur](https://i.imgur.com/tNibQgG.png)

**Comment by tianon** [comment]
Thanks to @zhsj this is fixed now! :tada: :heart:

**Comment by muru** [comment]
That's great! It would be nice to know how it was done. Asked GitHub or used Gitlab features?

**Comment by tianon** [comment]
<zhsj> I've contacted GitHub support, and
https://github.com/debian/apt is fixed now.

(from #debian-apt IRC)
