### ISSUE TITLE
Feature : Batch (un)installation

### ISSUE THREAD

**Issue by finn0** [Debian/apt#81]
Like 'pip' and 'npm ' if there would be feature in apt for (un)installation of list of pacakges from a file then this would be great feature when we have remove/install large number packages from a system. Yes, this can be done by using a simple script but inbuilt support will be nice.

**Comment by julian-klode** [comment]
um, just use xargs?

**Comment by julian-klode** [comment]
You can of course also build a source package control file, and then use apt-get build-dep with that file. which allows you to use the entire syntax for build dependencies. wohooo!
