### ISSUE TITLE
apt-key list --delete-expired-keys 6B73A36E6026DFCA not working

### ISSUE THREAD

**Issue by saydulk** [Debian/apt#82]
GPG error: http://www.rabbitmq.com/debian testing InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 6B73A36E6026DFCA

apt-key list --delete-expired-keys 6B73A36E6026DFCA

Not work for me Debian 9
![screenshot from 2019-01-26 01-56-51](https://user-images.githubusercontent.com/1058663/51769583-ac44eb00-210d-11e9-86da-185395d0d641.png)

**Comment by julian-klode** [comment]
I'm not sure what makes you think that `apt-key list --delete-expired-keys 6B73A36E6026DFCA` would do anything, or anything related to that issue. `apt-key list` lists the keys.

Ask your repository provider for a `.gpg` file containing their public keyring that you can drop into `trusted.gpg.d`
