### ISSUE TITLE
Setting wine-staging to use buster uses testing 

### ISSUE THREAD

**Issue by debianxfce** [Debian/apt#83]
apt 1.8.0~alpha3 (amd64)

xfce@ryzenpc:~$ cat /etc/apt/sources.list | grep wine
deb https://dl.winehq.org/wine-builds/debian/ buster main 
deb-src https://dl.winehq.org/wine-builds/debian/ buster main 

xfce@ryzenpc:~$ apt list wine-staging
Listing... Done
wine-staging/testing 4.0~rc7~buster amd64 [upgradable from: 4.0~buster]
wine-staging/testing 4.0~rc7~buster i386

You need to use the 4.0~buster version for each wine-staging package to upgrade from rc7.
sudo apt-get install wine-staging=4.0~buster

Problem is in apt or in the wine-staging server. Please check.
https://dl.winehq.org/wine-builds/debian/dists/

**Comment by julian-klode** [comment]
Please contact the wine people for questions about wine repositories.
