### ISSUE TITLE
"Conflicting distribution" warning when using a trivial repository

### ISSUE THREAD

**Issue by ianchildress** [Debian/apt#85]
The issue is related to using "trivial" repositories as referenced in https://www.debian.org/doc/manuals/repository-howto/repository-howto#using-a-repository

Example sources.list entry:
`deb [trusted=yes] file:///tmp/ repo/`

Result:
> W: Conflicting distribution: file:/tmp repo/ Release (expected repo/ but got stretch)

The issue:
https://github.com/Debian/apt/blob/master/apt-pkg/metaindex.cc#L86
`if (MaybeDist.empty() || this->Codename == MaybeDist || this->Suite == MaybeDist)`

It is expecting the first argument to be a Codename or Suite, but when using a trivial repository the first (and only) argument is the directory where the Release file can be found.

Expected behavior:
When there is only a single argument and contains a trailing slash, it should be handled as a trivial repository and not throw a warning.

**Comment by julian-klode** [comment]
That's #79

**Comment by ianchildress** [comment]
They throw the same warning but the cause and solution is different. I'll reply to the other issue if you would like to combine them.
