### ISSUE TITLE
A potential use of uninitialized bug

### ISSUE THREAD

**Issue by wurongxin1987** [Debian/apt#88]
![image](https://user-images.githubusercontent.com/4220002/54656823-1ff9e780-4b02-11e9-9ecc-f84df5795331.png)

The above code snippet can be also found in the latest version. In the source file policy.cc, if Pkg.VersionList() contains no element, the variable **cand** will not be initialized. The variable **cand** then will be returned to **GetShortDescription** function and assigned to the local variable **ver**. **ver** will be used at Line 219 in the source file private-output.cc.

**Comment by wurongxin1987** [comment]
@mvo5 @julian-klode  Can you help to check whether this is a true bug? Thanks.

**Comment by wurongxin1987** [comment]
Moreover, we observed that the function **GetLongDescription** has a safe guard (Line 240-241) to avoid the use of uninitialized variable.

![image](https://user-images.githubusercontent.com/4220002/54663493-652b1300-4b1c-11e9-8f04-b70b4c94612c.png)

**Comment by julian-klode** [comment]
This is C++ - The variable is initialized by the default constructor.
