### ISSUE TITLE
unable to debug for "Hash Sum Mismatch" error

### ISSUE THREAD

**Issue by eplaut** [Debian/apt#9]
I have tried using `debug.conf` contains
```
Debug::*::*  "true";
Debug::*  "true";
```
and also ```
apt-get -o Debug::pkgAcquire::Diffs=true -o Debug::Acquire::Transaction=true -o Debug::Acquire::HashSumMismatch=ture -o Debug::aptcdrom=true -o Debug::GetListOfFilesInDir=true update```
but i didn't got the required hash comparison output (apt-pkg/acquire-item.cc L 55)

**Comment by Arthur2e5** [comment]
Debian guys don't use the mirror for Issue Tracking and/or PRs. Use the [Debian BTS](https://www.debian.org/Bugs/) and send an email.

**Comment by julian-klode** [comment]
You have to set Debug::Acquire::HashSumMismatch=true (or yes, or 1). ture certainly is not true.

**Comment by julian-klode** [comment]
We also do not support wildcards in option names.
