### ISSUE TITLE
Debian 8 does not support OpenSSL > v1.0.1t

### ISSUE THREAD

**Issue by sunandabalu** [Debian/apt#90]
There is no way to upgrade OpenSSL on Debian 8 to anything greater than 1.0.1t. 
apt-get upgrade OpenSSL gives that its already on the latest and there is nothing to upgrade.

**Comment by DonKult** [comment]
Hi,

you reported to the developers of the package manager APT (as used in Debian and beyond), not to the developers of Debian in general or those involved with the packaging of OpenSSL in Debian. APT does what it is supposed to in this situation, so there is nothing we can do about that, hence closing.

That said, Debian 8.0 "jessie" is [no longer supported by the Debian project as a whole](https://www.debian.org/News/2018/20180601) for nearly a year. A subset of architectures and packages is covered by the [LTS effort](https://wiki.debian.org/LTS/Using) through. See there for details.

It is kinda the point of a distribution with fixed releases (like Debian stable or any other which isn't "rolling") to not introduce major version changes after the release, so staying at 1.0.1 seems perfectly normal to me. If you are worried about security bugs, those are covered by the backport of the relevant patches. Looks for me like the last one was in March. So, everything as it should be… ?

If you have questions about how that all works in more detail I recommend asking in one of the various different support channels (= mail, forum, IRC, …) available as an issue tracker isn't ideal for that.

Thanks for taking the time to report, for using APT (& Debian) and best regards

David Kalnischkies
