### ISSUE TITLE
README.md contains wrongly interpreted less than (<) and greater than (>) signs

### ISSUE THREAD

**Issue by jschleus** [Debian/apt#91]
In the README.md markdown file the line 57
```
Then you can use make as you normally would (pass -j <count> to perform <count>
```
contains less than (<) and greater than (>) signs in normal text that are wrongly interpreted if converted to HTML.

Probably they had to be escaped by a backslash or replaced by the HTML entities \&lt; and \&gt;.

See for e.g. https://github.com/Debian/apt/blob/master/README.md
where the \<count\> strings are just omitted.

**Comment by julian-klode** [comment]
Fixed in commit c11e2d67cef10629cf927d7f1a725e7bb094f266 - https://salsa.debian.org/apt-team/apt/commit/c11e2d67cef10629cf927d7f1a725e7bb094f266
