### ISSUE TITLE
Add option to get dependencies for 'apt download'

### ISSUE THREAD

**Issue by drzacek** [Debian/apt#92]
Add option to download packages for offline use along with all possible dependencies.

**Comment by julian-klode** [comment]
You mean install -d?

**Comment by drzacek** [comment]
no, 'install -d' seems to do something else, it downloads and stores the package in cache (don't know where exactly) so the system can later install it without downloading, while 'download' just plain downloads the .deb file to your current location.

**Comment by julian-klode** [comment]
Have you looked at apt-offline?

**Comment by drzacek** [comment]
Yes, but that's something totally different. And since apt already has option to install packages along with dependencies, why couldn't it download them too?

**Comment by julian-klode** [comment]
I'm not sure what you want then, so I'll close the issue.
