### ISSUE TITLE
Question on apt-get update

### ISSUE THREAD

**Issue by kavitha-r0573** [Debian/apt#97]
I am curious to know about the apt code so that I can contribute to this project and learn from it.

I have a question on "apt-get update" implementation. I did go through the code for a couple of days but couldn't get full clarity so need your help.

/var/lib/apt/lists - This contains two kinds of files. One set of files (* _Packages) that has the full package information with the short description. Another set of files (* _i18n_Translation-en) has just the full description for all the packages.

/var/cache/apt/ - This directory has two different caches (pkgcache.bin, srcpkgcache.bin). These are constructed from the information stored in the /var/lib/apt/lists directory.

**Here are my questions,**
1)  How does apt-cache create and updates the local package cache? Is it periodic or manual? As far as my investigation, it is manual (apt-get update).

fyi, I am using Linux 4.4.0-18362-Microsoft. "apt-config dump" command output doesn't show "APT::Cache::Generate".

2) When we run "apt-get update", does it download all the packages information that will be stored in /var/lib/apt/lists/* _Packages file? Is there a advanced logic, where client sends current state information (like all packageNames and their versions)? This is a puzzle as the code is very cryptic to understand.

I modified /var/lib/apt/lists/security.ubuntu.com_ubuntu_dists_xenial-security_restricted_binary-amd64_Packages (changed the version for one of the package) and ran "apt-get update" but it didn't revert my change.  Why?

This confirms, apt-get is looking at someother file to make the decision to update the /var/lib/apt/lists/* _Packages file.  When does the /var/lib/apt/lists/* _Packages file gets updated?

Can you explain whether it's expected behavior or not.

I did notice that the /var/cache/apt/pkgcache.bin (and srcpkgcache.bin) are updated everytime I run "apt-get update". 

3) What goes into pkgcache.bin and srcpkgcache.bin? I couldn't find any useful information in the internet. 

4) Why do we store the package full description in a different file? Is it because we want make cache faster that has only the short package description?

**Comment by DonKult** [comment]
I would suggest asking further question either on IRC on the OFTC network (like the rest of Debian) in #debian-apt or on the public mailinglist deity@lists.debian.org as that is where the APT developers hang out. Github is just a mirror for us – and issues here do not seem particularly suited for answering questions and keeping them accessible… Close – as I will with this one – sort-of disappear from view.

>     1. How does apt-cache create and updates the local package cache? Is it periodic or manual? As far as my investigation, it is manual (apt-get update).

All apt-* commands (re)create the cache files (pkgcache.bin & srcpkgcache.bin) if needed by default automatically from the files stored by "apt-get update" in /var/lib/apt/lists. The config option "APT::Cache::Generate" can be used to prevent that – usually with bad results as forcing the commands to work with old data usually results in incorrect results [aka: garbage in – garbage out].


>     1. When we run "apt-get update", does it download all the packages information that will be stored in /var/lib/apt/lists/* _Packages file? Is there a advanced logic, where client sends current state information (like all packageNames and their versions)? This is a puzzle as the code is very cryptic to understand.

The first file downloaded is the Release file (either as a clearsigned InRelease or in the form of Release and Release.gpg) which establishes that we really get the correct data later by being signed and containing checksums for all the files we want to get later in the process like the Packages files. The process is indeed complicated as we support different ways of saving bandwidth at the expense of diskspace & cputime and vice versa.

Note that "update" downloads information about ALL availables packages in the release. Nobody is told which packages are installed or in which version! If you want to share that information with your distribution (e.g Debian) have a look at the "popcon" package.

> I modified /var/lib/apt/lists/security.ubuntu.com_ubuntu_dists_xenial-security_restricted_binary-amd64_Packages (changed the version for one of the package) and ran "apt-get update" but it didn't revert my change. Why?

"update" requested the Release file and figured out that either a) the Release file didn't change, which means that the indexes can't have changed either or b) the Release file changed, but the new and the old version of the file contain the same checksum for this Packages file. As "update" sees the file on disk it assumes it has the expected checksum as it wouldn't be in that location if it wouldn't, so rechecking would be both pointless and a huge waste of cputime.

The next time the Packages file changes in the repository apt will pick that file up and override your changes – it might try patching first, but that will fail checksum checks.

> This confirms, apt-get is looking at someother file to make the decision to update the /var/lib/apt/lists/* _Packages file. When does the /var/lib/apt/lists/* _Packages file gets updated?

So, as you imagines and as I explained above, the Release file is responsible here.

>     1. What goes into pkgcache.bin and srcpkgcache.bin? I couldn't find any useful information in the internet.

They contain the most-used data from the files in /var/lib/apt/lists in a [binary] format apt can easily & quickly load at runtime to work with – and as mentioned are (re)created as needed: Most often by "update". pkgcache.bin is actually srcpkgcache.bin + data from /var/lib/dpkg/status as that file changes [potentially] a lot more often.
 
>     2. Why do we store the package full description in a different file? Is it because we want make cache faster that has only the short package description?

The description of a package changes a lot less often than other parts of metadata about the package like e.g. the version number. They can also have a considerable length, so some years ago we decided it is a good idea to have them all in another file which changes less often and hence also needs to be downloaded less often.
