### ISSUE TITLE
When does APT State gets updated?

### ISSUE THREAD

**Issue by kavitha-r0573** [Debian/apt#98]
/var/lib/apt/lists directory has two kinds of files (*_Packages, *_Translation-en).

/var/lib/apt/lists/*_Packages - contains the full package information with short description.

/var/lib/apt/lists/*_Translation_en - contains the full description for all the packages.

These files are used to build the cache files (/var/cache/apt/pkgcache.bin and srcpkgcache.bin ).

When do these files (/var/lib/apt/lists/*_Packages) get updated?

fyi, I modified one the package version number in /var/lib/apt/lists/*_Packages file. Then I ran "apt-get update" but my change is not reverted.

**Comment by DonKult** [comment]
I think I explained this in the answers for #97 already, so I will refer you there and save us both repeating myself here. :wink:
